from __future__ import annotations

from dataclasses import dataclass

from .classifiers import Classification, DeepReasoningClassifier, RuleBasedClassifier
from .contracts import ChatRequest, RouteDecision, ValidationResult
from .resource_manager import ResourceManager
from .validators import ConsistencyValidator, HallucinationValidator

ASSISTANT_NAMES = {
    "fast": "Worker Fast",
    "heavy": "Worker Heavy",
    "thinker": "Thinker",
    "architect": "Architect",
}


@dataclass
class RoutedChat:
    route: RouteDecision
    response_text: str
    validation: ValidationResult


class AgenticRouter:
    """Modular router with fast/slow classifiers and checksum validation."""

    def __init__(self, routing_policy: dict, role_registry: dict):
        self.routing_policy = routing_policy
        self.role_registry = role_registry
        self.rule_classifier = RuleBasedClassifier(routing_policy)
        self.deep_classifier = DeepReasoningClassifier()
        self.resources = ResourceManager()
        self.hallucination_validator = HallucinationValidator()
        self.consistency_validator = ConsistencyValidator()

    def route(self, req: ChatRequest) -> RouteDecision:
        classification = self._classify(req)
        force_big = classification.confidence < 0.75 or classification.role == "architect"
        lane = self.resources.select_lane(
            role=classification.role,
            complexity_score=classification.complexity_score,
            force_big_lane=force_big,
        )

        return RouteDecision(
            role_selected=classification.role,
            assistant_selected=ASSISTANT_NAMES.get(classification.role, "Unknown"),
            lane_selected=lane.lane,
            classifier_used=classification.classifier_name,
            confidence=round(classification.confidence, 3),
            reasons=classification.reasons + lane.reasons,
        )

    def route_and_respond(self, req: ChatRequest) -> RoutedChat:
        first_route = self.route(req)
        response_text = self._generate_stub_reply(first_route, req)

        combined_validation = self._validate(req.message, response_text)
        if not combined_validation.passed:
            # Single escalation step: move to planner lane when checksum fails.
            escalated = RouteDecision(
                role_selected="architect",
                assistant_selected=ASSISTANT_NAMES["architect"],
                lane_selected="big-indian",
                classifier_used=f"{first_route.classifier_used}+checksum-escalation",
                confidence=max(first_route.confidence, 0.8),
                reasons=first_route.reasons + ["checksum_failed_escalate_to_planner"],
            )
            response_text = self._generate_stub_reply(escalated, req)
            combined_validation = self._validate(req.message, response_text)
            return RoutedChat(route=escalated, response_text=response_text, validation=combined_validation)

        return RoutedChat(route=first_route, response_text=response_text, validation=combined_validation)

    def _classify(self, req: ChatRequest) -> Classification:
        first_pass = self.rule_classifier.classify(req)
        if first_pass.confidence >= 0.75:
            return first_pass
        return self.deep_classifier.classify(req, first_pass)

    def _generate_stub_reply(self, route: RouteDecision, req: ChatRequest) -> str:
        return (
            "[Scaffold reply] "
            f"assistant={route.assistant_selected} "
            f"role={route.role_selected} "
            f"lane={route.lane_selected}. "
            "This response is generated by the modular agentic router in mock mode. "
            f"Prompt preview: {req.message[:120]}"
        )

    def _validate(self, request_text: str, response_text: str) -> ValidationResult:
        hall = self.hallucination_validator.evaluate(request_text, response_text)
        cons = self.consistency_validator.evaluate(request_text, response_text)

        checks = {
            **{f"hallucination.{k}": v for k, v in hall.checks.items()},
            **{f"consistency.{k}": v for k, v in cons.checks.items()},
        }
        notes = hall.notes + cons.notes

        passed = hall.passed and cons.passed
        score = round((hall.score + cons.score) / 2.0, 3)
        return ValidationResult(passed=passed, score=score, checks=checks, notes=notes)
